# bicycle: 0.3
car: 0.3
motorcycle: 0.3
airplane: 0.3
bus: 0.3
train: 0.3
truck: 0.3
boat: 0.3
traffic light: 0.3
fire hydrant: 0.3
stop sign: 0.3
parking meter: 0.3
bench: 0.3
bird: 0.3
cat: 0.3
dog: 0.3
horse: 0.3
sheep: 0.3
cow: 0.3
elephant: 0.3
bear: 0.3
zebra: 0.3
giraffe: 0.3
backpack: 0.3
umbrella: 0.3
handbag: 0.3
tie: 0.3
suitcase: 0.3
frisbee: 0.3
skis: 0.3
snowboard: 0.3
sports ball: 0.3
kite: 0.3
baseball bat: 0.3
baseball glove: 0.3
skateboard: 0.3
surfboard: 0.3
tennis racket: 0.3
bottle: 0.3
wine glass: 0.3
cup: 0.3
fork: 0.3
knife: 0.3
spoon: 0.3
bowl: 0.3
banana: 0.3
apple: 0.3
sandwich: 0.3
orange: 0.3
broccoli: 0.3
carrot: 0.3
hot dog: 0.3
pizza: 0.3
donut: 0.3
cake: 0.3
chair: 0.3
couch: 0.3
potted plant: 0.3
bed: 0.3
dining table: 0.3
toilet: 0.3
tv: 0.3
laptop: 0.3
mouse: 0.3
remote: 0.3
keyboard: 0.3
cell phone: 0.3
microwave: 0.3
oven: 0.3
toaster: 0.3
sink: 0.3
refrigerator: 0.3
book: 0.3
clock: 0.3
vase: 0.3
scissors: 0.3
teddy bear: 0.3
hair drier: 0.3
toothbrush: 0.3